app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('members/', include('members.urls')),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from members import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('profile/', views.profile, name='profile'),
]

app/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('like/', views.post_like, name='post_like'),
]

app/members/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    img_profile = models.ImageField(
        upload_to="user",
        blank=True,
    )
    relation_users = models.ManyToManyField(
        'self',
        symmetrical=False,
    )
    mention = models.ForeignKey(
        'posts.Comment',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )


class UserRelation(models.Model):
    CHOICE_BLOCK_OR_FOLLOW = {
        ('f', 'Follow'),
        ('b', 'Block'),
    }

    to_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='to_user_relations',
        related_query_name='to_user_relation',
    )
    from_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='from_user_relations',
        related_query_name='from_user_relation',
    )
    relation_type = models.CharField(
        max_length=1,
        choices=CHOICE_BLOCK_OR_FOLLOW,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (
            ('to_user', 'from_user'),
        )

app/posts/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    photo = models.ImageField(
        upload_to='posts'
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_posts',
        related_query_name='like_post',
        through='PostLike',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk', ]

    def like_toggle(self, user):
        post_like, created = PostLike.objects.get_or_create(post=self, author=user)
        if not created:
            post_like.delete()
        return post_like


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    content = models.TextField()
    tags = models.ManyToManyField(
        'HashTag',
    )


class HashTag(models.Model):
    name = models.CharField(max_length=20)


class PostLike(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

app/members/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate

User = get_user_model()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'img_profile',
        ]

        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'img_profile': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file',
                }
            )
        }


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._user = None

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                "placeholder": "Username",
                "autofocus": "True",
            },
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
            }
        )
    )

    def clean(self):
        super().clean()
        user = authenticate(username=self.cleaned_data['username'], password=self.cleaned_data['password'])
        if user is None:
            raise forms.ValidationError('유저 검증에 실패하였습니다')
        self._user = user

    @property
    def user(self):
        if self._user is None:
            raise forms.ValidationError('검증 유저가 존재하지 않습니다.')
        return self._user

app/posts/forms.py
from django import forms

from posts.models import Post


class PostCreateForm(forms.Form):
    photo = forms.ImageField(
        widget= forms.ClearableFileInput(
            attrs={
                'class': 'form-control-file'
            }
        )
    )
    comment = forms.CharField(
        required=False,
        widget= forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': '3',
            }
        )
    )

    def save(self, author):
        post = Post.objects.create(
            author=author,
            photo=self.cleaned_data['photo'],
        )

        if self.cleaned_data.get('comment'):
            post.comment_set.create(
                author=author,
                content=self.cleaned_data['comment']
            )
        return post

app/members/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from members.forms import LoginForm, ProfileForm


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            user = form.user
            if user is not None:
                login(request, user)
                return redirect('posts:post_list')
    else:
        form = LoginForm()

    context = {
        'form': form
    }

    return render(request, 'members/login.html', context)


@login_required
def logout_view(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            logout(request)

    return redirect('members:login_view')


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()

    form = ProfileForm(instance=request.user)
    return render(request, 'members/profile.html', context={'form': form})

app/posts/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from posts.forms import PostCreateForm
from posts.models import Post


@login_required
def post_list(request):
    posts = Post.objects.filter(author__to_user_relation__from_user=request.user,
                                author__to_user_relation__relation_type='f') | Post.objects.filter(author=request.user)
    context = {
        'posts': posts
    }

    return render(request, 'posts/post_list.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostCreateForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(author=request.user)
            return redirect('posts:post_list')
    else:
        form = PostCreateForm()

    context = {
        'form': form
    }

    return render(request, 'posts/post_create.html', context)


@login_required
def post_like(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    post.like_toggle(request.user)

    context = {
        'like_count': post.like_users.count(),
    }

    return HttpResponse(json.dumps(context), content_type='application/json')

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Instagram</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Instagram</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'posts:post_create' %}">+ Add Post</a>
          {% else %}
          {% endif %}
      </nav>
      {% if user.is_authenticated %}
        <a class="btn btn-outline-primary mr-2" href="{% url 'members:profile' %}">Profile</a>
        <form action="{% url 'members:logout_view' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-primary" href="#">Logout</button>
        </form>
        {% else %}
        <a class="btn btn-outline-primary mr-2" href="{% url 'members:login_view' %}">Sign in</a>
            <a class="btn btn-outline-primary" href="#">Sign up</a>
        {% endif %}
    </div>
    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

app/templates/members/form_base.html
{% load static %}

<!doctype html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Instagram - Login</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/signin.css' %}">
</head>
<body class="text-center">
    {% block content %}
    {% endblock %}
</body>
</html>

app/templates/members/login.html
{% load static %}

<!doctype html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Instagram - Login</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/floating-labels.css' %}">
</head>
<body>
<form class="form-signin" action="{% url 'members:login_view' %}" method="POST">
    {% csrf_token %}
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">Login</h1>
    </div>

    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-primary" role="alert">
        {{ error }}
    </div>
    {% endfor %}
    {% endif %}

    {% for field in form %}
    <div class="form-label-group">
        {{ field }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    </div>
    {% endfor %}

    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted text-center">© 띠요오오옹</p>
</form>
</body>
</html>

app/templates/members/profile.html
{% extends 'members/form_base.html' %}
{% load static %}

{% block content %}
<form class="form-signin" action="{% url 'members:profile' %}" method="POST" enctype="multipart/form-data">
    <a href="{% url 'posts:post_list' %}"><img class="mb-4 text-center" src="{% static 'images/instagram.jpeg' %}" alt="" width="72" height="72"></a>
    {% csrf_token %}
    <div class="mb-4">
        <h1 class="h3 mb-3 font-weight-normal">Profile</h1>
    </div>

    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-primary" role="alert">
        {{ error }}
    </div>
    {% endfor %}
    {% endif %}

    {% for field in form %}
    <div class="form-label-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <button class="btn btn-lg btn-primary btn-block" type="submit">수정</button>
    <p class="mt-5 mb-3 text-muted text-center">© 띠요오오옹</p>
</form>
{% endblock %}

app/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="col">
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
        </div>
    {% endfor %}
        <button type="submit" class="btn btn-primary btn-lg btn-block">전송</button>
    </form>
</div>

{% endblock %}

app/templates/posts/post_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<div class="row">
    {% for post in posts %}
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img class="card-img-top"
                 alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;"
                 src="{{ post.photo.url }}"
                 data-holder-rendered="true">
            <div class="card-body">
                <p class="card-text">{{ post.author }}</p>
                <input type="button" class="like btn btn-sm btn-warning" name="{{ post.pk }}" value="Like">
                <span id="count-{{ post.id }}">{{ post.like_users.count }}개</span>


                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        {% if post.author == request.user %}
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        {% endif %}
                    </div>
                    <small class="text-muted">{{ post.created_at|naturaltime }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            type:"POST",
            url: "{% url 'posts:post_like' %}",
            data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: "json",
            success: function(response){
                $("#count-"+pk).html(response.like_count+"개");
                var users = $("#like-user-"+pk).text();
            }
        })
    })


</script>
{% endblock %}